spring:
  application:
    name: spring-ai
  config:
    import: optional:application-secret.yml
  ai:
    openai:
      embedding:
        options:
          model: text-embedding-ada-002
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.7
          max-tokens: 200

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection-name: vector_store
        initialize-schema: true
